import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Providers from "@/app/Providers";
import { Footer } from "@/components/Footer";
import { ImageKitProvider } from "@imagekit/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ImageKitProvider urlEndpoint={process.env.NEXT_PUBLIC_IMAGE_KIT_URL_END_POINT!}>
            <Providers>
              {/* <Navbar /> */}
              {children}
              {/* <Footer /> */}
            </Providers>
        </ImageKitProvider>
      </body>
    </html>
  );
}
